name: ai4beg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipywidgets=7.6.5
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - numpy=1.22.3
  - python=3.8.12
  - requests=2.26.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=58.0.4
  - tensorflow-base=2.3.0
  - pip:
    - -r requirements.txt
